cc_binary(
    name = "main",
    srcs = [
        "textadventure-main.cc",
    ],
    deps = [
        ":lib",
    ],
)

cc_library(
    name = "lib",
    srcs = [
        "state.cc",
        "scene.cc",
    ],
    hdrs = [
        "action.h",
        "scene.h",
        "state.h",
    ],
    deps = [],
)
