cc_binary(
    name = "main",
    srcs = [
        "main.cc",
    ],
    deps = [
        ":lib",
    ],
)

cc_library(
    name = "lib",
    srcs = [
        "all_actions.cc",
        "all_scenes.cc",
        "opening_scene.cc",
        "scene.cc",
        "state.cc",
    ],
    hdrs = [
        "action.h",
        "all_actions.h",
        "all_scenes.h",
        "opening_scene.h",
        "scene.h",
        "state.h",
    ],
    deps = [],
)
